#!/bin/bash
cd $home
for var  in $(cat /root/boot_env) ; do export $var ; done

if [[ "$fresh_install" == "yes" ]];then
	su discourse -c 'bundle install --deployment --retry 3 --jobs 4 --verbose --without test development'
	DEV_RAKE='/var/www/discourse/vendor/bundle/ruby/2.6.0/gems/railties-6.0.1/lib/rails/tasks/dev.rake'
	if [[ -f $DEV_RAKE ]] ;then
	        echo " $DEV_RAKE file is exist "
	else
        	echo " $DEV_RAKE file does not exist "
        	cp /.dev.rake $DEV_RAKE
        	chown discourse:discourse $DEV_RAKE
	fi
	su discourse -c 'bundle exec rake db:migrate'
	su discourse -c 'bundle exec rake assets:precompile'
fi

chown -R discourse:www-data /shared/log/rails
PATH=$PATH:$home/bin LD_PRELOAD=$RUBY_ALLOCATOR HOME=/home/discourse USER=discourse exec thpoff chpst -u discourse:www-data -U discourse:www-data bundle exec config/unicorn_launcher -E production -c config/unicorn.conf.rb

