#!/bin/bash    

presearch_dir="/root/Presearch"
out=$(docker pull presearch/node:latest | grep -i "Status")
ts=`date "+%A, %d-%m-%Y %X"`

if [[ $out == *"up to date"* ]]; then
   echo "$ts - Image is updated already"
else
   echo "$ts - Updating Image . . "
   docker build -t arrajput/presearch:latest $presearch_dir
   docker push arrajput/presearch:latest
   # docker image prune -f
fi
