#!/usr/bin/env bash
#pkill -9 digibyte
#sleep 1
#/opt/dgb/bin/digibyted -conf=/dgb/digibyte.conf -rpcuser=$rpcuser -rpcpassword=$rpcpasswd > /dev/null 2>&1
sleep 1
if pgrep -x "digibyted" > /dev/null
then
    echo "OK"
else
    echo "NO"
fi
