#!/usr/bin/env bash
port=`netstat -lntpe | grep -w "35000" | awk '{print $4}' | cut -d ":" -f 2`

if [ -z $port ]; then echo "Service not running . . "; exit 1;fi

if [ $port -eq 35000 ]
then
    echo "OK" > /tmp/checkp2p
else
    echo "NO" > /tmp/checkp2p
fi
