#!/usr/bin/env bash
port=`netstat -lntpe | grep -w "9999" | awk '{print $4}' | cut -d ":" -f 2`

if [ -z $port ]; then echo "Service not running . . "; exit 1;fi

if [ $port -eq 9999 ]
then
    echo "OK" > /tmp/checksse
else
    echo "NO" > /tmp/checksee
fi
