#!/usr/bin/env bash
echo "deb https://repo.casperlabs.io/releases" bionic main | sudo tee -a /etc/apt/sources.list.d/casper.list
curl -O https://repo.casperlabs.io/casper-repo-pubkey.asc
apt-key add casper-repo-pubkey.asc
apt-get -y update
apt install -y casper-client casper-node-launcher 

while read protocol_version; do sudo -u casper /etc/casper/pull_casper_node_version.sh casper.conf $protocol_version; sudo -u casper /etc/casper/config_from_example.sh $protocol_version; done < <(curl -sf genesis.casperlabs.io/casper/protocol_versions)

sudo -u casper casper-client keygen /etc/casper/validator_keys

sudo sed -i "/trusted_hash =/c\trusted_hash = '$(casper-client get-block --node-address http://$KNOWN_VALIDATOR_IP:7777 -b 20 | jq -r .result.block.hash | tr -d '\n')'" /etc/casper/1_0_0/config.toml

sudo logrotate -f /etc/logrotate.d/casper-node
