FROM base

# required to build the ipxe template
RUN apk add --no-cache bash git make openssl gcc perl coreutils musl-dev xz-dev syslinux xorriso
# Required to create the sqlite database
RUN apk add --no-cache sqlite

