#!/usr/bin/env bash
port=`netstat -lntpe | grep -w "8888" | awk '{print $4}' | cut -d ":" -f 2`

if [ -z $port ]; then echo "Service not running . . "; exit 1;fi

if [ $port -eq 8888 ]
then
    echo "OK" > /tmp/checkrest
else
    echo "NO" > /tmp/checkrest
fi
