#!/usr/bin/env bash
set -ex

## Set version and network
CASPER_VERSION=2_0_4
CASPER_NETWORK=casper

### Add Casper repository and install packages
echo "deb [arch=amd64] https://repo.casper.network/releases $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/casper.list
curl -fsSL https://repo.casper.network/casper-repo-pubkey.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/casper.gpg
sudo apt update
sudo apt install -y casper-node-launcher casper-client

### Create casper user if it doesn't exist
id -u casper &>/dev/null || sudo useradd -m -d /etc/casper casper
