#!/usr/bin/env bash
set -ex
CASPER_VERSION=2_0_4
CASPER_NETWORK=casper

# Frontend
cat /opt/cronjobs | crontab -
rm -f /var/www/html/index.html
if [ ! -d "/run/lock" ]; then
    mkdir /run/lock
fi
/usr/bin/checkheaders
/usr/bin/checkip
/etc/init.d/apache2 start
/etc/init.d/cron start
chmod 777 /tmp/*

### Generate node keys (only if they don't exist)
cd /etc/casper/validator_keys
if [ ! -f secret_key.pem ]; then
    sudo -u casper casper-client keygen .
fi


### Set up configuration
sudo -u casper /etc/casper/node_util.py stage_protocols $CASPER_NETWORK.conf

### Get known validator IP
KNOWN_ADDRESSES=$(sudo -u casper cat /etc/casper/$CASPER_VERSION/config.toml | grep known_addresses)
KNOWN_VALIDATOR_IPS=$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<< "$KNOWN_ADDRESSES")
# Get reachable validator ip
KNOWN_VALIDATOR_IPS_ARRAY=($KNOWN_VALIDATOR_IPS)
for server_ip in "${KNOWN_VALIDATOR_IPS_ARRAY[@]}"
do
  :
  if nc -zv -w5 "$server_ip" 7777 > /dev/null 2>&1
    then
        KNOWN_VALIDATOR_IP=$server_ip;
        break;
    fi 
done

# Check knownvalidator ip was found and set
if [ -z ${KNOWN_VALIDATOR_IP} ]; then exit 1; fi

# Get trusted_hash into config.toml (only if valid)
TRUSTED_HASH=$(casper-client get-block --node-address http://$KNOWN_VALIDATOR_IP:7777 -b 4494833 | jq -r .result.block.hash | tr -d '\n')
if [ -n "$TRUSTED_HASH" ] && [ "$TRUSTED_HASH" != "null" ]; then 
    sudo -u casper sed -i "/trusted_hash =/c\trusted_hash = '$TRUSTED_HASH'" /etc/casper/$CASPER_VERSION/config.toml
fi



### Start the node
sudo /etc/casper/node_util.py rotate_logs
exec casper-node-launcher -f 2.0.4
