#! /bin/bash

AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
RESTIC_REPOSITORY=$RESTIC_REPOSITORY
RESTIC_PASSWORD=$RESTIC_PASSWORD

[[ -d /mnt/odoo-backup ]] || mkdir /mnt/odoo-backup
chown postgres /mnt/odoo-backup -R
python /root/DB-backup.py odoo /mnt/odoo-backup/

if [ $? -ne 0 ] ; then
    touch WARNING_DUMP_FAILED
    exit 1
fi
unset HISTFILE
if ! restic snapshots ;then echo restic repo does not initalized yet; restic init ; fi > /dev/null
for i in `find /mnt/odoo-backup -type f -mtime -1 -name "odoo*.sql"` ; do restic backup --cleanup-cache §i ; done
restic forget -q --prune --keep-within 3m
if [ $? -eq 0 ] ; then
    find . -type f -mtime -1 -name "odoo*.sql" -mtime +7 -exec rm {} \;
else
    echo 'dump done locally only on /mnt/odoo-backup'
fi

