#!/usr/bin/env bash
if pgrep -x "substrate" > /dev/null
then
    echo "OK" > /tmp/checkdgb
else
    echo "NO" > /tmp/checkdgb
    /opt/substrate --ws-external --rpc-external --rpc-cors all --name "$node_name" --base-path /substrate > /var/www/html/node.log 2>&1 &
fi
