services:
  mariadb-master:
    image: mariadb:latest
    container_name: mariadb-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - master-data:/var/lib/mysql
    networks:
      - monitoring

  mariadb-slave:
    image: mariadb:latest
    container_name: mariadb-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: mariadb-master
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: password
      MYSQL_DATABASE: mydb
    depends_on:
      - mariadb-master
    networks:
      - monitoring

  mariadb_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mariadb_exporter
    command:
      - "--mysqld.username=user:password"
      - "--mysqld.address=mariadb-master:3306"
    ports:
      - "9104:9104"
    depends_on:
      - mariadb-master

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/dashboards:/var/lib/grafana/dashboards

volumes:
  master-data:

networks:
  monitoring:
    driver: bridge