#!/usr/bin/env bash
#curl -s localhost:9615/metrics | grep -i "sync_target" | awk '{print $2}' > /tmp/checkheaders
curl -s localhost:9615/metrics | grep -i "finalized" | awk '{print $2}' > /tmp/checkblocks
